apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-alertmanager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-alertmanager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mcp-alertmanager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- tpl (toYaml .) . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mcp-alertmanager.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- tpl (toYaml .) . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- tpl (toYaml .) . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mcp-alertmanager.serviceAccountName" . }}
      securityContext:
        {{- tpl (toYaml (default .Values.defaultPodSecurityContext .Values.podSecurityContext)) . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- tpl (toYaml (default .Values.defaultSecurityContext .Values.securityContext)) . | nindent 12 }}
          image: "{{ template "mcp-alertmanager.image" .Values.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          args:
            - "--port={{ .Values.service.port }}"
            - "--log-level={{ .Values.server.logLevel }}"
            {{- if .Values.alertmanager.url }}
            - "--url={{ .Values.alertmanager.url }}"
            {{- else }}
            - "--namespace={{ .Values.alertmanager.namespace }}"
            - "--service={{ .Values.alertmanager.service }}"
            - "--service-port={{ .Values.alertmanager.servicePort }}"
            - "--service-scheme={{ .Values.alertmanager.serviceScheme }}"
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
      {{- with .Values.extraContainers }}
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
